plugins {
	id 'org.springframework.statemachine.module'
}

description = 'Spring Statemachine Autoconfigure'

dependencies {
	management platform(project(":spring-statemachine-platform"))
	api project(':spring-statemachine-core')
	api 'org.springframework.boot:spring-boot-autoconfigure'
	api 'org.springframework.boot:spring-boot-actuator-autoconfigure'
	api 'org.springframework.boot:spring-boot-actuator'
	optional 'io.micrometer:micrometer-core'
	testImplementation 'org.springframework.boot:spring-boot-test'
	testImplementation 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core'
}
