plugins {
	id "base"
	id 'ch.unibas.medizin.universe.statemachine.root'
	id 'maven-publish'
}

description = 'Universe Statemachine'

repositories {
	maven { url = 'https://repo.spring.io/release' }
	mavenCentral()
}

allprojects {
	group = 'ch.unibas.medizin.universe.statemachine'

	repositories {
		maven { url = 'https://repo.spring.io/release' }
		mavenCentral()
	}

	configurations.configureEach {
		resolutionStrategy.cacheChangingModulesFor 1, 'hours'
	}
}
