version=0.0.1
springBootVersion=4.1.0

jakartaPersistenceVersion=3.2.0
eclipseEmfXmiVersion=2.40.0
eclipseUml2CommonVersion=2.0.0-v20140602-0749
eclipseEmfCommonVersion=2.45.0
eclipseUml2TypesVersion=2.0.0-v20140602-0749
eclipseEmfEcoreVersion=2.42.0
eclipseUml2UmlVersion=5.0.0-v20140602-0749
curatorVersion=5.9.0
springAsciidoctorBackends=0.0.7
awaitilityVersion=4.3.0
reactorBlockHoundVersion=1.0.17.RELEASE
findbugsVersion=3.0.2
