pluginManagement {
	repositories {
        maven { url = 'https://repo.spring.io/snapshot' }
		maven { url = 'https://repo.spring.io/release' }
		mavenCentral()
		gradlePluginPortal()
	}
	plugins {
		id 'org.springframework.boot' version "$springBootVersion"
	}
}

rootProject.name = 'universe-statemachine'

include 'universe-statemachine-platform'
include 'universe-statemachine-core'
include 'universe-statemachine-autoconfigure'
include 'universe-statemachine-starter'

rootProject.children.each { project ->
	project.buildFileName = "${project.name}.gradle"
}
