plugins {
	id 'ch.unibas.medizin.universe.statemachine.starter'
}

description = 'Universe Statemachine Starter'

dependencies {
	management platform(project(":universe-statemachine-platform"))
	api(project(":universe-statemachine-autoconfigure"))
	api 'org.springframework.boot:spring-boot-starter'
}
