plugins {
	id "java-gradle-plugin"
	id "java"
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
	gradlePluginPortal()
	mavenCentral()
	maven { url = 'https://repo.spring.io/plugins-release/' }
}

ext {
	if (project.hasProperty('springBootVersion')) {
		set("springBootVersion", springBootVersion)
	}
	else {
		def propertiesFile = new File(new File("$projectDir").parentFile, "gradle.properties")
		propertiesFile.withInputStream {
			def properties = new Properties()
			properties.load(it)
			set("springBootVersion", properties["springBootVersion"])
		}
	}
}

dependencies {
	implementation(platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}"))
	implementation("org.springframework:spring-core")
	implementation 'org.asciidoctor.jvm.convert:org.asciidoctor.jvm.convert.gradle.plugin:4.0.5'
	implementation 'com.jfrog.artifactory:com.jfrog.artifactory.gradle.plugin:6.0.4'
	implementation "org.springframework.boot:org.springframework.boot.gradle.plugin:${springBootVersion}"
}

gradlePlugin {
	plugins {
		modulePlugin {
			id = "ch.unibas.medizin.universe.statemachine.module"
			implementationClass = "ch.unibas.medizin.universe.statemachine.gradle.ModulePlugin"
		}
		starterPlugin {
			id = "ch.unibas.medizin.universe.statemachine.starter"
			implementationClass = "ch.unibas.medizin.universe.statemachine.gradle.StarterPlugin"
		}
		bomPlugin {
			id = "ch.unibas.medizin.universe.statemachine.bom"
			implementationClass = "ch.unibas.medizin.universe.statemachine.gradle.BomPlugin"
		}
		docsPlugin {
			id = "ch.unibas.medizin.universe.statemachine.docs"
			implementationClass = "ch.unibas.medizin.universe.statemachine.gradle.DocsPlugin"
		}
		distPlugin {
			id = "ch.unibas.medizin.universe.statemachine.root"
			implementationClass = "ch.unibas.medizin.universe.statemachine.gradle.RootPlugin"
		}
		samplePlugin {
			id = "ch.unibas.medizin.universe.statemachine.sample"
			implementationClass = "ch.unibas.medizin.universe.statemachine.gradle.SamplePlugin"
		}
	}
}
