name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Spring Gradle Build Action
      uses: spring-io/spring-gradle-build-action@v2
      with:
        java-version: '25'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew clean build
